title: Formal Philosophy
description: Tutorials on the philosophy of formal methods, with concrete metaphors and executable models.
theme: jekyll-theme-primer
url: https://thedarklightx.github.io
baseurl: /Formal_Methods_Philosophy
